baseUrl: /green_egypt/api/v1
server:
  port: 8097
spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      mvc:
        routes:
#        ############################# Tips Service #############################
         - id: TIPS-SERVICE
           uri: lb://tips-service
           predicates:
             - Path= ${baseUrl}/tips/**
#        ############################# User Service #############################
         - id: USER-SERVICE
           uri: lb://user-service
           predicates:
             - Path= ${baseUrl}/users/**
#         ############################# User Service #############################
         - id: TRANSACTION-SERVICE
           uri: lb://transaction-service
           predicates:
             - Path= ${baseUrl}/transactions/**


